# docker-compose.yml
# Use root/example as user/password credentials
version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mongo_db
    ports:
      - 27017:27017  

